// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySimpleAlbumStore.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MySimpleAlbumStore.API.Migrations
{
    [DbContext(typeof(AlbumStoreContext))]
    [Migration("20240603173413_seedingArtistsToAlbums")]
    partial class seedingArtistsToAlbums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MySimpleAlbumStore.API.Models.Album", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = new Guid("738ea536-f44c-45ab-bfc5-e856f483bad0"),
                            ArtistId = new Guid("b109cacf-33b4-4004-9b8a-2a030220e765"),
                            ImageUrl = "https://example.com/album1.jpg",
                            Title = "Album 1"
                        },
                        new
                        {
                            AlbumId = new Guid("88326a7d-79d5-4c7f-a7e2-d0e04f1836ac"),
                            ArtistId = new Guid("ed1d9c53-2ea8-42c4-9596-728d4c0e839e"),
                            ImageUrl = "https://example.com/album2.jpg",
                            Title = "Album 2"
                        });
                });

            modelBuilder.Entity("MySimpleAlbumStore.API.Models.Artist", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = new Guid("b109cacf-33b4-4004-9b8a-2a030220e765"),
                            Name = "John Smith"
                        },
                        new
                        {
                            ArtistId = new Guid("ed1d9c53-2ea8-42c4-9596-728d4c0e839e"),
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("MySimpleAlbumStore.API.Models.Album", b =>
                {
                    b.HasOne("MySimpleAlbumStore.API.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MySimpleAlbumStore.API.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
