// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySimpleAlbumStore.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MySimpleAlbumStore.API.Migrations
{
    [DbContext(typeof(AlbumStoreContext))]
    partial class AlbumStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MySimpleAlbumStore.API.Models.Album", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = new Guid("a3084d34-c610-4408-aaee-0624117bc1cf"),
                            ArtistId = new Guid("21f04af8-8d28-4465-a098-da58fe86388c"),
                            ImageUrl = "https://example.com/album1.jpg",
                            Title = "Album 1"
                        },
                        new
                        {
                            AlbumId = new Guid("3eeb18da-97b2-44cb-a9f1-dfc5234e04f7"),
                            ArtistId = new Guid("822e1f8a-d8d6-4adc-8740-9ca68cbf9f61"),
                            ImageUrl = "https://example.com/album2.jpg",
                            Title = "Album 2"
                        });
                });

            modelBuilder.Entity("MySimpleAlbumStore.API.Models.Artist", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = new Guid("21f04af8-8d28-4465-a098-da58fe86388c"),
                            Name = "John Smith"
                        },
                        new
                        {
                            ArtistId = new Guid("822e1f8a-d8d6-4adc-8740-9ca68cbf9f61"),
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("MySimpleAlbumStore.API.Models.Album", b =>
                {
                    b.HasOne("MySimpleAlbumStore.API.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MySimpleAlbumStore.API.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
